version: '3.7'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    volumes:
      #- 'mariadb_data:/bitnami'
      - './volumes/mariadb_data:/bitnami'

  redmine:
    #image: 'docker.io/bitnami/redmine:4-debian-10'
    build:
      context: ./redmine
      args:
        - HTTP_PROXY=${HTTP_PROXY:-}
        - http_proxy=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
        - https_proxy=${HTTPS_PROXY:-}
        - NO_PROXY=${NO_PROXY:-}
        - no_proxy=${NO_PROXY:-}
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - REDMINE_USERNAME=admin
      - REDMINE_EMAIL=admin@example.com
      - REDMINE_LANGUAGE=ja
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
    ports:
      - '${REDMINE_PORT:-80}:3000'
    volumes:
      #- 'redmine_data:/bitnami'
      - './volumes/redmine_data:/bitnami'
    depends_on:
      - mariadb

#volumes:
#  mariadb_data:
#    driver: local
#  redmine_data:
#    driver: local
